---
services:
- name: app1
  description: This is App1
  virtual_host: app1.service.dev
- name: app2
  description: This is App2
  virtual_host: app2.service.dev
- name: app3
  description: This is App3
  virtual_host: app3.service.dev
description: This is for use in gui_api
